### ISSUE TITLE
Unexpected behavior with re-used runners - `cannot run ssh: No such file or director`

### ISSUE THREAD

**Issue by zeekhuge** [knatnetwork/github-runner#1]
Hi ! Thanks for this repo and simplifying the process of hosting github-runners. 

Most of the workflows that I have use some github-based private packages, which the package manager fetches over ssh. To test the same I created workflow which would just try to clone some private github package over ssh :

```yml
name : "Run dummy jobs"

on: 
  workflow_dispatch:
  push:
    branches: 
      - main

jobs:
  dummy-job:
    strategy:
      matrix:
        sleep-seconds: [40, 41, 42, 43, 44]
    runs-on: self-hosted
    steps:
      - name: Sleep for ${{ matrix.sleep-seconds }} seconds
        run: |
          sleep ${{ matrix.sleep-seconds }}
  
  github-access-related-job:
    strategy:
      matrix:
        output: [output_1, output_2, output_3, output_4]
    runs-on: self-hosted
    defaults:
      run:
        shell: bash
    steps:
      - name: Create SSH key
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.some-secret }}" | base64 --decode > ~/.ssh/id_rsa
          
      - name: Git clone
        run: |
          git clone git@github.com:org/package-1 ${{ matrix.output }}-package-1
          git clone ssh://git@github.com/org/package-2 ${{ matrix.output }}-package-2
```

When the above described workflow gets executed on a fresh-new runner, the workflow works fine. However, if the same workflow gets executed on a runner that is getting re-used (the additional-args already include `--ephemeral`), I get the following error :

> error: cannot run ssh: No such file or directory
> fatal: unable to fork
> Error: Process completed with exit code 128.

Any idea whats happening here ? The `openssl-client` is already installed on the runners. I guessed the `PATH` is getting messed up, but then even `git` should not have been accessible.

Any pointer will be appreciated greatly. Thanks.
